### ISSUE TITLE
`lang` is not a good idea

### ISSUE THREAD

**Issue by zhaoda** [rtCamp/gitbook-plugin-edit-link#11]
The `lang` is not a good idea beacuse i have not lang path.

``` js
                var lang = $('html').attr('lang');
                if (lang) lang = lang + '/';
```

**Comment by deathbeam** [comment]
@zhaoda check my open PR here: https://github.com/rtCamp/gitbook-plugin-edit-link/pull/10

**Comment by zhaoda** [comment]
@rtCamp

**Comment by zhaoda** [comment]
Use gitbook-plugin-editlink instead https://github.com/zhaoda/gitbook-plugin-editlink
