### ISSUE TITLE
hook page:after does not exist in gitbook 2.0.1

### ISSUE THREAD

**Issue by friedger** [rtCamp/gitbook-plugin-edit-link#3]
There is page:before and page as a hook, but not page:after
The edit link does not work for me e.g. on http://gdg-wisdom.gitbooks.io/gdg-wisdom-2015/content/what_is_a_gdg/organizing.html

**Comment by rahul286** [comment]
I have added an issue https://github.com/GitbookIO/gitbook/issues/724

Also, I am digging into gitbook code at the moment.

I hope to fix this soon.

**Comment by rahul286** [comment]
I couldn't fix it for now but if you wish to use old versions for time being, you can do following:

### Install gitbook 1.5.0

`npm -g install gitbook@1.5.0`

### Update `book.json` file to use old version of edit-link plugin

Pasting a sample below:

``` json
{
  "gitbook": "1.5.0",
  "plugins": ["edit-link@1.1.0","-mathjax"],
  "pluginsConfig": {
        "edit-link": {
          "base": "https://github.com/wpveda/book/edit/master/content",
          "label": "Edit This Page"
        },
        "ga": {
          "token": "UA-59804046-1"
        }
  }
}
```

**Comment by rahul286** [comment]
@friedger you can use new version 1.3.0 which has a workaround contributed by @todvora

**Comment by friedger** [comment]
Great! Works for us.
