### ISSUE TITLE
Link in PDF

### ISSUE THREAD

**Issue by aschempp** [rtCamp/gitbook-plugin-edit-link#5]
The edit link is also added when generating the PDF, which is not necessary in my opinion. Is there a way to remove it?

**Comment by rahul286** [comment]
@aschempp I am sorry for the issue but I need more time to look into this. As I never used PDF functionality so far, I did not test this plugin with PDF.

May I know which gitbook version you have used? We have 2 different version of codes for different gitbook version.

By the way, if you manage to find a fix, please send a pull request and I will update plugin immediately.

**Comment by aschempp** [comment]
I'm using the latest version (2.0.x). The solution is pretty simple, it just needs the following code at the top of the _page_ function:

``` js
if (this.options.generator != 'website') {
    return;
}
```

**Comment by todvora** [comment]
Exactly, I wanted to suggest the same thing. I am just not sure, if the plugin should return `page` or nothing in this case. I tested this solution and works also OK:

``` javascript
if(this.config.options.generator !== 'website') {
    return page;
}
```

Just for the documentation, as a workaround, one can also attach custom CSS style to a book and hide the link itself. In the book.json:

``` javascript
"styles": {
    "pdf": "pdf.css"
}
```

And the pdf.css content should be then 

``` css
#edit-link {display:none}
```

Best regards,
Tomas

**Comment by aschempp** [comment]
see #6
